apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trinooperator-cluster-role
  namespace: default
rules:
  - apiGroups:
      - trino-group.tofel.tech
      - apps
      - ""
      - networking.k8s.io
    resources:
      - trino-operators
      - trino-operators/status
      - deployments
      - services
      - ingresses
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
